#version: '2.2'
#services:
#  web:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    image: web
#    ports:
#      - 8080:8080
#    networks:
#      - app
#
#networks:
#  app:

version: '2'

services:
  config-server:
    build:
      context: .
      dockerfile: ./config-server/Dockerfile
    image: config-server
    container_name: config-server
    mem_limit: 512M
    ports:
      - 8888:8888

  eureka-server:
    build:
      context: .
      dockerfile: ./eureka-server/Dockerfile
    image: eureka-server
    container_name: eureka-server
    mem_limit: 512M
    depends_on:
      - config-server
    ports:
      - 8761:8761

  customers-service:
    build:
      context: .
      dockerfile: ./customers-service/Dockerfile
    image: customers-service
    container_name: customers-service
    mem_limit: 512M
    depends_on:
      - config-server
      - eureka-server
    ports:
      - 8081:8081

  visits-service:
    build:
      context: .
      dockerfile: ./customers-service/Dockerfile
    image: visits-service
    container_name: visits-service
    mem_limit: 512M
    depends_on:
      - config-server
      - eureka-server
    ports:
      - 8082:8082

  vets-service:
    build:
      context: .
      dockerfile: ./vets-service/Dockerfile
    image: vets-service
    container_name: vets-service
    mem_limit: 512M
    depends_on:
      - config-server
      - eureka-server
    ports:
      - 8083:8083

  zuul-server:
    build:
      context: .
      dockerfile: ./zuul-server/Dockerfile
    image: zuul-server
    container_name: api-gateway
    mem_limit: 512M
    depends_on:
      - config-server
      - eureka-server
    ports:
      - 8080:8080

  admin-server:
    build:
      context: .
      dockerfile: ./admin-server/Dockerfile
    image: admin-server
    container_name: admin-server
    mem_limit: 512M
    depends_on:
      - config-server
      - eureka-server
    ports:
      - 9090:9090
