version: '2.1'

services:
  config-server:
    build:
      context: .
      dockerfile: ./config-server/Dockerfile
    image: config-server
    container_name: config-server
    mem_limit: 512M
    ports:
      - 8888:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-server:8888/actuator/health"]
      interval: 200s
      timeout: 200s
      retries: 5

  eureka-server:
    build:
      context: .
      dockerfile: ./eureka-server/Dockerfile
    image: eureka-server
    container_name: eureka-server
    mem_limit: 512M
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - 8761:8761
    healthcheck:
      test: ["CMD", "curl", "-f","http://eureka-server:8761/actuator/health"]
      interval: 200s
      timeout: 200s
      retries: 5

  customers-service:
    build:
      context: .
      dockerfile: ./customers-service/Dockerfile
    image: customers-service
    container_name: customers-service
    mem_limit: 512M
    depends_on:
#      config-server:
#        condition: service_healthy
      eureka-server:
        condition: service_healthy
    ports:
      - 8081:8081

  visits-service:
    build:
      context: .
      dockerfile: ./visits-service/Dockerfile
    image: visits-service
    container_name: visits-service
    mem_limit: 512M
    depends_on:
#      config-server:
#        condition: service_healthy
      eureka-server:
        condition: service_healthy
    ports:
      - 8082:8082

  vets-service:
    build:
      context: .
      dockerfile: ./vets-service/Dockerfile
    image: vets-service
    container_name: vets-service
    mem_limit: 512M
    depends_on:
#      config-server:
#        condition: service_healthy
      eureka-server:
        condition: service_healthy
    ports:
      - 8083:8083

  zuul-server:
    build:
      context: .
      dockerfile: ./zuul-server/Dockerfile
    image: zuul-server
    container_name: zuul-server
    mem_limit: 512M
    depends_on:
#      config-server:
#        condition: service_healthy
      eureka-server:
        condition: service_healthy
    ports:
      - 8080:8080

  admin-server:
    build:
      context: .
      dockerfile: ./admin-server/Dockerfile
    image: admin-server
    container_name: admin-server
    mem_limit: 512M
    depends_on:
#      config-server:
#        condition: service_healthy
      eureka-server:
        condition: service_healthy
    ports:
      - 9090:9090
